### ISSUE TITLE
TLS skp flag

### ISSUE THREAD

**Issue by hestiacloud** [MaggotMouth/sentry-exporter#20]
Hi,

Great work here! Is it possible to add tls skip flag?

Thank you!

**Comment by MaggotMouth** [comment]
Hi,

Can you please provide more context/information about the problem you're having?

**Comment by hestiacloud** [comment]
Hi, thank you for getting back so fast! We have internal sentry host with self signed certs and I communicate with API by using curl -k flag. Is there a way to configure your exporter to use insecure communication?

**Comment by MaggotMouth** [comment]
There isn't currently a flag to skip TLS as the Sentry API client does not explicitly define such a flag.
Can you confirm that the exporter is currently not working for you, without such a flag?  Self signed certs should be fine.

**Comment by hestiacloud** [comment]
Thank you for getting back to me again! We managed to fix this problem. For anyone struggling with this , the following were the steps we followed:

1. Download the self-signed **root ca** of our self-hosted Sentry via Chrome (you can follow https://medium.com/@menakajain/export-download-ssl-certificate-from-server-site-url-bcfc41ea46a2 . We saved it in base64 format. That will require you to use PEM in the next command.)
2. Covert the downloaded file from .cer to .crt by running `openssl x509 -inform PEM -in ../cert.cer -out ../sentry-cert.crt` ( you might need either PEM or DER https://stackoverflow.com/questions/642284/do-i-need-to-convert-cer-to-crt-for-apache-ssl-certificates-if-so-how
3. Move this file to the host that the sentry exporter is running on (in our case just a linux machine, for docker you might need to follow different steps?)
3. Ensure that the cert is moved to /etc/pki/ca-trust/source/anchors/
4. Run `update-ca-trust extract` command 
5. Try the curl without -k and it is all working well. If you have any issues make sure that you've downloaded the root ca.

I'm sure there are better/easier ways to do this, but this worked for us. Thank you for being so responsive, great project!

**Comment by hestiacloud** [comment]
I have another question (I can open new issue if that's better?). Is it possible to add sentry labels that are associated with the errors? We have label env=dev/prod and we would like to distinguish these per number of errors firing. Is that in any way realistic?

**Comment by MaggotMouth** [comment]
Unfortunately that won't be possible.  Labels are only available when listing all the errors, which would mean individually counting the errors instead of just fetching the counts.
This endpoint exposes the tag information: https://docs.sentry.io/api/events/list-a-projects-events/
This is the endpoint this exporter uses:  https://docs.sentry.io/api/projects/retrieve-event-counts-for-a-project/

Additionally, it probably wouldn't be a good idea to split per label as the cardinality of the metric could become too large.
In the case of a small organisation that consists of 5 projects and 5 teams you could end up with 100 unique series, if you add tags to that it could inflate to 500 before you know it.
Now imagine you have 50 projects and 10 teams.

**Comment by hestiacloud** [comment]
Fair enough, I understand. Thank you for a great exporter :)
